- name: Build Archive
      env:
        API_KEY_ID: ${{ secrets.APP_STORE_CONNECT_API_KEY_ID }}
        API_ISSUER_ID: ${{ secrets.APP_STORE_CONNECT_API_ISSUER_ID }}
      run: |
        xcodebuild archive \
          -project GrowPAR.xcodeproj \
          -scheme GrowPAR \
          -configuration Release \
          -archivePath "$RUNNER_TEMP/GrowPAR.xcarchive" \
          -destination "generic/platform=iOS" \
          -allowProvisioningUpdates \
          -authenticationKeyPath ~/.appstoreconnect/private_keys/AuthKey_${API_KEY_ID}.p8 \
          -authenticationKeyID "$API_KEY_ID" \
          -authenticationKeyIssuerID "$API_ISSUER_ID" \
          CODE_SIGN_STYLE=Automatic \
          DEVELOPMENT_TEAM=UKMP287GQD \
          COMPILER_INDEX_STORE_ENABLE=NO \
          ENABLE_PREVIEWS=NO \
          EXCLUDED_ARCHS__EFFECTIVE_PLATFORM_SUFFIX_simulator__NATIVE_ARCH_64_BIT_x86_64=x86_64 \
          EXCLUDED_ARCHS=$(uname -m)
